### ISSUE TITLE
Should integrate with String an Array classes

### ISSUE THREAD

**Issue by lukelex** [rodrigoalvesvieira/cep_facil#3]
The CEP should be retrievable through the string containing its value and also through a collection of strings.

**Comment by rodrigoalvesvieira** [comment]
Can you provide an example of your possible solution?

**Comment by abacha** [comment]
the API doesn't support multiple requests, so it will have to iterate over an array and make multiple requests.
I don't think this is a gem`s responsibility

**Comment by lukelex** [comment]
But we should be able to do like so, '29080-821'.get_address()

**Comment by abacha** [comment]
to use like that you need to create a method on the String Class, I don't see when you won`t be able to use as get_address('xxxx')

**Comment by rodrigoalvesvieira** [comment]
I don't think that monkey patching the String class just to add this method is any reasonable.
