### ISSUE TITLE
Problema com encoding

### ISSUE THREAD

**Issue by klebershimabuku** [rodrigoalvesvieira/cep_facil#7]
Estou encontrando um problema na codificação de alguns caracteres.

por exemplo, para o cep: 01040010

realizando um `.inspect` obtenho a seguinte saída:

```
#<CepFacil::API:0x007f53e8fe4500   @read="status=encontrado&cep=01040010&tipo=Rua&uf=SP&cidade=S\xC3\xA3o Paulo&bairro=Rep\xC3\xBAblica&descricao=do Botic\xC3\xA1rio", @data={"status"=>"encontrado", "cep"=>"01040010", "tipo"=>"Rua", "uf"=>"SP", "cidade"=>"S\xC3\xA3o Paulo", "bairro"=>"Rep\xC3\xBAblica", "descricao"=>"do Botic\xC3\xA1rio"}>
```

tenho `#encoding: utf-8` no controller e para efeito de teste, coloquei também na view, porém, o resultado é o mesmo.
#### Ambiente:

> Ubuntu 12.04
> rails 3.2.3
> ruby 1.9.2p290

Alguma idéia do que possa ser?

**Comment by rodrigoalvesvieira** [comment]
Olá Kleber,

ter `#encoding: utf-8` não resolve porque o problema realmente vem do CepFacil. Eu sinceramente não sei como resolver esse problema no momento porém, aparentemente, os dados só aparecem com codificação corrompida no objeto `CepFacil` retornado. Eis o resultado do meu experimento:

``` ruby
token = "q1w2e3r4t5y6u7i8o9p0"
cep = "01040010"
```

``` ruby
endereco = CepFacil::API.new cep, token
```

retorno:

```
#<CepFacil::API:0x007fd21b3a4770 @read="status=encontrado&cep=01040010&tipo=Rua&uf=SP&cidade=S\xC3\xA3o Paulo&bairro=Rep\xC3\xBAblica&descricao=do Botic\xC3\xA1rio", @data={"status"=>"encontrado", "cep"=>"01040010", "tipo"=>"Rua", "uf"=>"SP", "cidade"=>"S\xC3\xA3o Paulo", "bairro"=>"Rep\xC3\xBAblica", "descricao"=>"do Botic\xC3\xA1rio"}>
```

acessando propriedades do objeto retornado diretamente eu consigo ler dados normalmente:

``` ruby
endereco.descricao
```

Você consegue também?

**Comment by klebershimabuku** [comment]
Sim, acessando diretamente pelas propriedades o retorno está vindo corretamente.

Mas seria interessante ter o retorno correto também no objeto `CepFacil`.

Vou dar uma pesquisada depois pra ver se consigo algum resultado positivo com relação à isso.

Obrigado.

**Comment by rodrigoalvesvieira** [comment]
Pois é, vou pesquisar também. Esse problema tem que ser resolvido logo mas pelo menos como está agora não está tão crítico.

Obrigado.
