### ISSUE TITLE
CEP de Cidade

### ISSUE THREAD

**Issue by vlaube** [rodrigoalvesvieira/cep_facil#8]
Deveria retornar dados para o CEP 17700-000 (Osvaldo Cruz)?

Localidade: Osvaldo Cruz
UF: SP
CEP:    17700-000

**Comment by rodrigoalvesvieira** [comment]
@vlaube deveria sim. Esse problema não é com a gem mas sim com o Webservice CepFácil. Eu sugiro [entrar em contato](http://cepfacil.com.br/default.aspx#contato) com eles e reportar essa falha.
